name: Starlight CD pipeline

on:
  push:
    branches:
      - "dev"
      - "*ci*"
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc-13]
    steps:
      - uses: actions/checkout@v2
      - name: Set scripts permissions
        run: chmod +x ./bin/*
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Install system dependencies
        run: ./bin/deps.sh
      - name: Run tests and benchmarks
        run: KSTD_RUN_BENCHMARKS=1 ./bin/build.sh
      - name: Generate code coverage
        run:

      - name: Upload code coverage
        run: |
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} \
            -n 'service'-${{ github.run_id }} -F service -f ./coverage/coverage.xml
